### PR TITLE
Chore/Streamline launcher icons

### PR DESCRIPTION
**Pull request by friedger**
* Use the same icon for all demos to make them recognisable
* Use one launcher icon for all screens
* Use same name for launcher icon

device-2015-07-07-094805

### CODE REVIEW

**Comment by blundell** [comment]
@DigitalPencils what do you think?

**Comment by ryanbateman** [comment]
Let's try to steer away from any other company's IP (in this case, Megaman). It doesn't look particularly professional.

**Comment by xrigau** [comment]
@ryanbateman so serious

**Comment by blundell** [comment]
super srs but true

**Comment by friedger** [comment]
Waiting for a new proposed launcher icon for the android demos @DigitalPencils

**Pull request closed without merging**
