### PR TITLE
13/Links to NOS demos

### PR DESCRIPTION
**Pull request by friedger**
This PR adds links to demos of the NOS libraries and projects

### CODE REVIEW

**Comment by friedger** [comment]
depends on #9 and https://github.com/novoda/novoda/pull/12

**Comment by xrigau** [comment]
@friedger this can be reopened now?

**Comment by friedger** [comment]
Still depends on #9 @xavi

**Comment by friedger** [comment]
@xrigau

**Comment by xrigau** [comment]
:sweat_smile:

**Comment by friedger** [comment]
@xrigau reopened

**Comment by xrigau** [comment]
nice :+1: :shipit:

**Pull request merged**
